[package]
name = "puzzlefs"
version = "0.1.0"
authors = ["Tycho Andersen <tycho@tycho.pizza>"]
edition = "2018"

[dependencies]
anyhow = "*"
nix = "*"
clap = { version = "4.0.18", features = ["derive"] }
daemonize = "0.4"
ctrlc = "3.2.0"
log = "0.4.17"
env_logger = "0.9.3"
format = { path = "../format" }
builder = { path = "../builder" }
oci = { path = "../oci" }
reader = { path = "../reader" }
extractor = { path = "../extractor" }

[dev-dependencies]
docker_extract = "*"
assert_cmd = "*"
dir-diff = "*"
tempfile = "*"
