[package]
name = "puzzlefs"
version = "0.1.0"
authors = ["Tycho Andersen <tycho@tycho.pizza>"]
edition = "2018"

[dependencies]
anyhow = "*"
nix = "*"
clap = "3.0.0-beta.2"
daemonize = "0.4"
format = { path = "../format" }
builder = { path = "../builder" }
oci = { path = "../oci" }
reader = { path = "../reader" }
extractor = { path = "../extractor" }

[dev-dependencies]
docker_extract = "*"
assert_cmd = "*"
dir-diff = "*"
tempfile = "*"
