name: ci

on:
    push:
    pull_request:
    schedule:
        - cron: '0 0 * * 0' # weekly

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: nightly
                components: clippy, rustfmt
            - name: install dependencies
              run: |
                sudo apt-get install libfuse-dev libzstd-dev libxxhash-dev skopeo umoci
            - run: make lint check
